eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:7777/eureka}

okta:
  oauth2:
    issuer: https://dev-88423786.okta.com/oauth2/default
    audience: api://default